/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-107587-g6ca1690643-avbuild"
#endif /* AVUTIL_FFVERSION_H */
